const ROLES=['CITIZEN','ADMIN','OFFICER','SUPER_ADMIN'];
const CATEGORIES=['ROADS','GARBAGE','WATER','DRAINAGE','ELECTRICITY','STREET_LIGHT','PUBLIC_PROPERTY','TRAFFIC','SANITATION','OTHER'];
const STATUSES=['SUBMITTED','UNDER_REVIEW','ASSIGNED','IN_PROGRESS','RESOLVED','REJECTED','REOPENED'];
const SEVERITIES=['LOW','MEDIUM','HIGH','CRITICAL']; const PRIORITIES=['LOW','MEDIUM','HIGH','URGENT'];
const DEPARTMENT_BY_CATEGORY={ROADS:'Public Works',GARBAGE:'Sanitation',WATER:'Water Supply',DRAINAGE:'Drainage',ELECTRICITY:'Electricity',STREET_LIGHT:'Electricity',PUBLIC_PROPERTY:'Municipal Services',TRAFFIC:'Roads',SANITATION:'Sanitation',OTHER:'Municipal Services'};
module.exports={ROLES,CATEGORIES,STATUSES,SEVERITIES,PRIORITIES,DEPARTMENT_BY_CATEGORY};
